# Generated by Django 3.2 on 2021-08-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('seccion_electoral', models.CharField(max_length=4, verbose_name='Seccion Electoral')),
                ('zona', models.CharField(max_length=2, verbose_name='Zona')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_tarjeta', models.IntegerField(blank=True, verbose_name='folio de tarjeta')),
                ('beneficio', models.CharField(max_length=50)),
                ('beneficiario', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tarjeta.persona')),
            ],
        ),
    ]
