# Generated by Django 3.2 on 2021-08-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='folio_tarjeta',
            field=models.IntegerField(verbose_name='folio de tarjeta'),
        ),
    ]
