# Generated by Django 3.2 on 2021-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta', '0002_alter_tarjeta_folio_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='folio_tarjeta',
            field=models.IntegerField(blank=True, verbose_name='folio de tarjeta'),
        ),
    ]
