# Generated by Django 3.2.4 on 2021-10-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta', '0004_persona_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=10, null=True, verbose_name='Direccion'),
        ),
    ]
