# Generated by Django 3.2.4 on 2021-10-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta', '0005_persona_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido_paterno',
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=80, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
